# ===================================================================
# IMPORTANT SETUP INSTRUCTIONS
#
# After cloning the project, make a copy of this file.
# Rename the copy to 'application.yaml'.
# Then, fill in your local database credentials below.
# ===================================================================

spring :
  application :
      name : store
  datasource:
    url: jdbc:mysql://localhost:3306/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USER_NAME
    password: YOUR_DATABASE_PASSWORD
  jpa:
    show-sql: true